version: "3.7"

services:
  app:
    image: lob-test
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: my_test_password
    command:
      ["/app/utils/wait-for-it.sh", "mysql:3306", "--", "/app/utils/test.sh"] 
  mysql:
    image: mysql:8.0
    volumes:
      - lob-mysql-test-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_test_password
      MYSQL_DATABASE: labyrinth-of-babel

volumes:
  lob-mysql-test-data: