version: "3.7"

services:
  app:
    image: lob
    ports:
      - 80:80
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: labyrinth_of_babel
    command:
      ["/app/utils/wait-for-it.sh", "mysql:3306", "--", "/app/bin/lob"]
  mysql:
    image: mysql:8.0
    command: --init-file /data/application/init.sql
    volumes:
      - lob-mysql-data:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: my_password

volumes:
  lob-mysql-data: