version: "3.7"

services:
  app:
    image: lob-test
    ports:
      - 80:80
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: labyrinth_of_babel_test
    command:
      ["/app/utils/wait-for-it.sh", "mysql:3306", "--", "/app/utils/test.sh"] 
  mysql:
    image: mysql:8.0
    volumes:
      - lob-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password

volumes:
  lob-mysql-data: